### ISSUE TITLE
Suppressredirect (Hauptmodul)

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#10]
Nachdem der Benutzer einen Auftrag gestellt hat, wird eine Seite aus seinem eigenen BNR ohne Weiterleitung verschoben, Missbrauch wird dadurch verhindert, das nur in eine Richtung verschoben wird.

**Comment by MGChecker** [comment]
LUKE; QAS MACHST DU GERADE?

**Comment by Luke081515** [comment]
Status: 50% Fertig. Das Modul an sich geht, jetzt muss nur noch eien Einschränkung für den eigenen BNR vorgenommen werden.

**Comment by Luke081515** [comment]
Abgeschlossen, läuft stabil auf Beta.
