### ISSUE TITLE
Berechtigungen

### ISSUE THREAD

**Issue by MGChecker** [Luke081515/Luke081515Bot#11]
Wir haben nun einige Ideen, die auf Portale abgestimmt sind:

* Blacklist(s) anlegen und bearbeiten
* Glashüttenverschiebungen beantragen

Wie die Berechtigungen hierzu angelegt werden, würde ich gern in einem eigenen Issue angehen, da es Modulübegreifend ist. Darum gibt es dieses Issue nun. 

Eine Möglichkeit,die mich persönlich jedoch noch nicht zufrieden stellt wäre, die Bearbeitungen auf editor zu beschränken. Dies ist mir jedoch zu allgemein und kann gerade wegen Außenstehenden, die die Portalrichtlinien nicht genau kennen, problematisch werden. 

Darum schlage ich vor, dass auch Blacklistbearbeitungen (wobei vorher noch festgelegt werden muss wie die Blacklists genau aufgebaut sind) genau wie Verschiebungen über die Warteschlange laufen. Berechtigt, einen solchen Request zu tätigen sind alle Nutzer, die auf einer bestimmten Liste stehen, die nur im Bot selbst bearbeitet werden kann. Dabei hat jedes Portal eine solche Liste (oder 2, da 2 getrennte Aufgaben) für sich. 

Wie diese Rechte vergeben werden, muss ebenfalls geklärt werden, ich erklär das hier mal so, als wäre jedes Portal ein eigenes Wiki. Es gibt mehrere Möglichkeiten: Entweder die Rechte werden durch Stewards vergeben, nachdem eine vom Portal getragene Anfrage zu den Rechten gestellt wurde. Oder es gibt *auch* Bürokraten, die die Vergabe für ihr Portal entweder nach eigenem Ermessen oder nach Konsens durchführen können. Dabei gibt es den Unterschied, dass letzteres vollautomatisch über die Warteschlange geschähe, während für ersteres immer du nötig wärst. Oder alternativ wird die Gruppe der Stewards ausgeweitet, sodass nach Bestätigung des durch einen beliebigen User für einen beliebigen User getätigten Request durch einen Steward der Auftrag vollautomatisch ausgeführt wird.

Was hältst du von diesen Ideen, und welche Cariante würdest du bevorzugen?

**Comment by MGChecker** [comment]
Also mit dem Meilenstein hat das jetzt eher weniger zu tun, für die Grundfunktionalität (BNR) wird es ja nicht benötigt.

**Comment by MGChecker** [comment]
Es wäre nett, wenn du mal etwas hierzu sagen könntest. Außerdem schätzt du die Priorität zu niedrig ein, diese Frage muss vor Glashütten und Blacklist geklärt sein.

**Comment by Luke081515** [comment]
Naja, erstmal wird das Modul ohne Glashütten fertig gestellt, denn bevor ich nicht die Berechtigung habe, es einzusetzen, werde ich es nicht weiterentwickeln, sonst ist die Arbeit nachher für die Katz. Deshalb ist die Priorität erstmal niedrig. Wenn ich dann die Genehmigung habe, überdenke ich die Priorität dann.

**Comment by MGChecker** [comment]
Siehe suppressredirect-Issue.

**Comment by Luke081515** [comment]
Ähm, du willst Rechte durch Stewards verteilen lassen? Finde ich nicht so gut. Ich wollte eigentlich bei Verschiebungen nur eine ignoreList machen, die ein js Format hat, und im meinem BNR ist, so das sie nur durch mich oder einen Admin bearbeitet werden kann. Ich könnte natürlich auch noch zusätzlich eine Whitelist zum selben Prinzip machen, aber anders würde ich es nicht machen.

**Comment by MGChecker** [comment]
Ich glaube du hast mich ganz falsch verstanden. xDD Stewards und Bürokraten sind nicht die aus der Wikipedia, sondern Sinnbilder, die für Rechtegruppen stehen. Lies den Teil nochmal genau durch.

**Comment by Luke081515** [comment]
oh, da hab ich danebengelesen :-). Ich würds so machen, wie bei der Steward Methode, ich bin der Steward und trage das beim Konsens in meine js datei ein. Allerdings tendiere ich eher zur Blacklist, ich könnte als Berechtigte alle Mitlgieder des Projekts ansehen

**Comment by MGChecker** [comment]
Mir gefällt die Bürokratenmethode am besten. Fortsetzung folgt...
