### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by MGChecker** [Luke081515/Luke081515Bot#13]
Wenn ich das richtig sehe, sind mehrere Releases geplant, in denen mehrere Issues zusammengfasst sind.

* Version 1.0: #4, #10 und #14 
* Version 1.5: #12 und #11
* Version 2.0: #7 und #8 

Ist das so in etwa richtig?

**Comment by Luke081515** [comment]
Ja, wobei ich an der Stelle sehen muss, ob (in deiner Version jetzt) erst 1.5 oder 2.0 kommt, da bin ich mir noch nicht sicher....

**Comment by MGChecker** [comment]
Ich denke, #11 muss sowieso vor #8 fertig sein, und ich denke es ist als Submodul leichter zu programmieren, als die Sache mit der zudem noch unfertigen Infobox..

**Comment by Luke081515** [comment]
Hm, zumindest die Grundfunktion allgemein für Infoboxen könnte ich aber schon programmieren, dazu gehört auch das Kat auslesen....

**Comment by Luke081515** [comment]
Realeses mache ich jetzt bei jeder neuen Funktion.
