### ISSUE TITLE
InfoboxCheckTool (ParameterChecker 1)

### ISSUE THREAD

**Issue by MGChecker** [Luke081515/Luke081515Bot#15]
Das InfoboxCheckTool checkt alle Artikel, wo eine Infobox eingebaut ist, auf die Gefülltheit der erforderlichen Parameter.

**Comment by Luke081515** [comment]
Dann brauche ich mal alle Paramter die das checken soll....

**Comment by MGChecker** [comment]
Okay, kommt.
