### ISSUE TITLE
InfoboxCheckTool (Hier alle Vorschläge zum Tool rein)

### ISSUE THREAD

**Issue by MGChecker** [Luke081515/Luke081515Bot#2]
Ich stelle mir ein Tool vor, dass die Infobox Youtube-Kanal auf unterscheidlichste Faktoren alle drei Tage überprüft und dabei über die Funktionalitäten von TemplateData hinausgeht. Seine Ergebnisse trägt er in ienen speziellen Abschnitt auf der QSYT ein:

**Einbindungen und Kategrorisierungen**
* Befinden sich alle Seiten in denen die Box eingebunden ist, in der Kategorie: YouTube?
* Ist in allen Seiten dieser Kategorie die Infobox eingebunden?
* Für beides gibt es eine Blacklist, die keinen ToDo-Punkt ergibt.

**Parameter**
* Sind die Parameter Genre, Kanäle, Abonennten, Aufrufe, Videos ausgefüllt?
* Format regelgerecht (Hierzu muss man sich noch Gedanken machen)
* Es gibt eine Blacklist

**Relevanz**
* Haben Channels genug Abonennten oder aufrufe?
* Blacklist sehr wichtig

**Botgetriebene Infoboxerweiterungen**
* Abos und Aufrufe lassen sich direkt aus YT auslesen
* Aktualisierung oder Hinzufügung der Parameter / botbetriebene Infoboxen erstellen
* Videos habe ich noch keine Mglk. gefunden

**Comment by Luke081515** [comment]
OK, ich schau mir das mal an, allerdings hat die Warteschlange da Priorität, die stelle ich vorher fertig.

**Comment by Luke081515** [comment]
Betreiber lass ich mal drin, auch solche Boxen kann es geben.... Ich kümmere mich dann zuerst um das feststellen der Vollständigkeit, das mit Relevant oder nicht kommt erst später, und erst wenn die Kriterien klar sind :-)

**Comment by Luke081515** [comment]
hm, bei der Relevanz, Auswerten nach Whitelist, Blacklist, oder eins von beiden in Kombination mit einer KAT Auswertung?
