### ISSUE TITLE
Suppressredirect (Hier alle Vorschläge zum Tool rein)

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#3]
Unterdrückt Weiterleitungen beim Verschieben von Seiten aus dem eigenen BNR, Benutzer können mit einer ignore List ausgeschlossen werden.

**Comment by MGChecker** [comment]
Eine präzisere Beschreibung würde nicht schaden. Um einen Entwurf für den K. kümmere ich mich Montag oder Dienstag.

**Comment by Luke081515** [comment]
Ja, bei Glashütten würde ich ein Submodul anlegen. Aber erst wenn das Hauptmodul durch ist.

**Comment by MGChecker** [comment]
Schön. Auf Antrag durch das Portal dann? Sonst könnte das zu Widerstand führen.

**Comment by MGChecker** [comment]
Was hältst du davon, dass der Bot in der Zusammenfassungszeile angibt, wer ihn beauftragt hat? Und sollte er durch ihn durchgeführte Aktionen auf Antrag innerhalb eines bestimmten Zeitrahmens wieder rückgäng machen dürfen?

**Comment by Luke081515** [comment]
Die Beauftragung ist zumindest bei Verschieben aus dem BNR gegeben, da da der Benutzer selbst den Auftrag stellen muss. Bei Glshütten dagegen wird die Funktion nur bei Konsens eingeführt, dort müsste dann ein DiffLink auf den Auftrag oder der Auftraggeber stehen, das kommt dann extra. Rückgängig machen geht einfach durch rückverschiebung, da muss dann ein Admin die WL löschen, das sollte ein ausreichender Kontrollmechanismus sein.

**Comment by MGChecker** [comment]
Ich halte diese Vorgehensweise bei Glashütten nicht für sinnvoll, näheres folgt.

**Comment by MGChecker** [comment]
Darf man erfahren, was das Labeljonglieren soll, wa imo völlog sinnlos ist?

**Comment by MGChecker** [comment]
Gerade bin ich aggro, da mein letzter umfangreichet Comment einfach beim Speichern gelöschþ wurde und plötzlich ein Teil der Issies weg war

**Comment by MGChecker** [comment]
Das mit den Glashütten ist so mMn Unfug.

**Comment by MGChecker** [comment]
Ich bin dafür, dass eine Verschiebung aus Glashütten, keine Konsensdiskussion benötigt. Ich arbeite selbst in einem WikiProjekt mit Glashütte und kann sagen, dass zumeist aufgrund ihrer Unnötigkeit keine Diskussion stattfindet. Außerdem: Wo ist der Unterschied, ob eine solche Seite mit oder ohne WL verschoben wird? Letzendlich muss ich die Idee aber im Projekt vortragen, was sowas entscheidet. Eine Befugtenliste wäre mMn eine gute Lösung. DiffDiskussionsshit würde außerdem viel länger benötigen als Verschiebung + SLA. Die Rückgängigmachung von Botaktionen halte ich jedoch für sehr wichtig, vielleicht später als Submodulm

**Comment by MGChecker** [comment]
Und jetzz stand der Text plötzlich wieder im Bearbeitungsfenster :D

**Comment by Luke081515** [comment]
Naja, ich meinte auch, das man nicht für das Verschieben einen Konsens brauch, sondern allgemein dafür, das das Modul für die Glashütte freigeschaltet wird. Das mit der Befugtenliste muss ich mal schauen.

**Comment by MGChecker** [comment]
Ok.

**Comment by MGChecker** [comment]
Was hältst du von der Idee, dass der Bot eigene Aktionen auf Atrag rückgängig machen kann? IMO ist das wirklich sehr sinnvoll. Ansonsten werde ich mal WP:WPCS kontaktieren, ob sie sich ein solches Feature vorstellen können. Willst du das für Film und Fernsehen übernehmen?

**Comment by Luke081515** [comment]
Und kannst ja mal vorsichtig fragen. Zu dem rückgänig machen: Jeder Benutzer der autoconfirmed hat, kann eine rückverschiebung einleiten, dann müsste halt die WL gelöscht werden, aber so viel Kontrolle halte ich für notwendig.
