### ISSUE TITLE
Getrennte Austragung bei der Benachrichtigung ermöglichen

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#41]
Es sollen zwei Listen verfügbar sein, auf denen man sich austragen kann, so das es möglich ist, das man nur Benachrichtigt wird, wenn die Verschiebung fehlerhaft war.

**Comment by MGChecker** [comment]
Ser gute Idee.

**Comment by Luke081515** [comment]
Nicht meine: https://de.wikipedia.org/wiki/Benutzer_Diskussion:Merlissimo#Es_gab_Fehler_bei_der_Bearbeitung_deines_Auftrages
