### ISSUE TITLE
UserAnalysator

### ISSUE THREAD

**Issue by MGChecker** [Luke081515/Luke081515Bot#5]
Ein Tool, was eine umfangreiche Analyse über einen Benutzer tätigt, die diesem dann per E-Mail weitergegeben werden. Dabei werden Namensräume, Kategroeien, Logbucheinträge etc. berücksichtigt.

**Comment by Luke081515** [comment]
Vorerst geschlossen, bis der Rest abgearbeitet, dann öffne ich es wieder.
