### ISSUE TITLE
InfoboxCheckTool

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#7]
Diese Tool überprüft die Infoboxen eines Fachbereiches, und erstellt daraus eine Worklist, in der fehlende Parameter und sonstige Mängel aufgelistet werden. Die Auswertung erfolgt mittels Kategorien.

**Comment by MGChecker** [comment]
Das hat in Teilen sehr wenig mit dem zu tun, was ich im Übersichtsthread geschrieben habe.

**Comment by Luke081515** [comment]
Naja, aber es ist erstmal die Grundfunktion, der rest wird dann ergänzt

**Comment by MGChecker** [comment]
Was heißt es jetzt eigtl. für mich, wenn du lockst. Kannst du bitte noch einmal präzisieren, was du mit dem letzten Satz meinst?

**Comment by Luke081515** [comment]
Also, wenn ich locke, heißt das, das ich den Auftrag genau so bearbeiten möchte, und nach Möglichkeit keine Weiteren Kommentare haben möchte. Zu dem anderen: Es geht um das Modul allgemein, d.h. es soll so sein, das ich es auch für Redaktionen übernehmen kann, das YT Spezifische, z.B. Paramtere prüfen, gehört nicht mehr zum Allgemeinen...

**Comment by MGChecker** [comment]
Achso. Dann finde ich aber, dass du zu viel lockst. Bevor die Einzelheiten geklärt sind.

**Comment by MGChecker** [comment]
Willst du dieses Tool in seiner ersten Version ohne Blacklist releasen? Keine gute Idee.

**Comment by Luke081515** [comment]
Die kommt schon dazu, nur das ist ein Subauftrag, der gentrennt aufgelistet ist. Dennoch mache ich vor dem ersten Realese eine Blacklist mit rein.
