### ISSUE TITLE
InfoboxCheckTool (Ergänzung um eine Blacklist)

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#8]
Ermöglicht das Ausnehmen von Artikel mittels einer Blacklist im BNR des Bots, für jedes Projekt existiert dann eine eigene Blacklist.

**Comment by MGChecker** [comment]
Es sind getrennte Blacklists nötig.

**Comment by MGChecker** [comment]
Ist es geplant, die Blacklist auf einzelne Teilaufgaben einschränkbar zu machen? Ich hielte das für sehr sinnvoll. Viwlleicht sollten Blacklist-Requests auch per Warteschlange getätigt werden? Dann ließen sich aufs Portal abgestimmte berechtigte Benutzer festlegen, wie schon bei den Glashütten.  Eventuell kann man eine Berechtigtenliste für beides zusammen machen. Wie man die erweitern/einschränken kann, müsste man sich dann überlegen. Es ist jedoch IMO eine bessere Lösung als edit=editor.

**Comment by Luke081515** [comment]
Ja, ich wollte die Blacklists aufteilen.

**Comment by MGChecker** [comment]
Eine Blacklist für jedes Portal oder noch feiner zwisxlchen unterschiedlichen Fehlern differenziert?

**Comment by Luke081515** [comment]
Nach einzelenen Tasks, aber nicht zu fein. Ich muss dann mal schauen.

**Comment by MGChecker** [comment]
Ok. Die Berechtigung für Einträge in diese Blacklist ist ja vorerst nicht Teil dieses Tasks, sondern gehört zu #11
