### ISSUE TITLE
Feststellen der Relevanz im Bereich YouTube

### ISSUE THREAD

**Issue by Luke081515** [Luke081515/Luke081515Bot#9]
Das Tool prüft anhand der Parameter, ob Relevanz durch Abosnentenzahlen oder Aufrufe vorliegt. Im Falle einer Medienrelevanz muss die Blacklist um einen Eintrag ergänzt werden.

**Comment by MGChecker** [comment]
Die RKs werden eh so schnell nicht fertig.

**Comment by Luke081515** [comment]
Gesagt und getan
